### PR TITLE
Mr.IT Guy's first commit to Python Directory

### PR DESCRIPTION
**Pull request by aathil-Mr-ITGuy**
these are answers for question from Codeacademy classes

### CODE REVIEW

**Review by swaaz — CHANGES_REQUESTED** [review]
You have done a really good job. But you have created pr directly to `mater` not `hacktoberfest` branch. Also, It would be better if you add simple and short programs like [this](https://github.com/swaaz/basicprograms/tree/master/C) . Make those changes then its ready to merge.

**Comment by aathil-Mr-ITGuy** [comment]
Hi thanks for the changes, can you let me know how to push into hacktober first branch, TYA

**Comment by swaaz** [comment]
> Hi thanks for the changes, can you let me know how to push into hacktoberfest branch, TYA

check the path here
image

**Comment by swaaz** [comment]
Feel free to open pull request once you do changes

**Pull request closed without merging**
